; PROGRAM :: PROGRAM TO CREATE A FILE (INPUT FILE) AND TO DELETE AN
; EXISTING FILE...

.MODEL SMALL

DISPLAY MACRO MSG
        LEA DX, MSG
        MOV AH, 09H
        INT 21H
ENDM

.DATA
MSG1 DB 0DH, 0AH, "ENTER THE FILE NAME           :: $"
MSG2 DB 0DH, 0AH, "FILE CREATED SUCCESSFULLY  $"
MSG3 DB 0DH, 0AH, "CREATION FAILED.$"
MSG4 DB 0DH, 0AH, "ENTER THE FILE NAME TO DELETE :: $"
MSG5 DB 0DH, 0AH, "DELETED SUCCESSFULLY $"
MSG6 DB 0DH, 0AH, "DELETION FAILED $"
FNAME DB 40H DUP(?)
FNAME2 DB 40H DUP(?)

.CODE
START : MOV AX, @DATA
        MOV DS, AX
        DISPLAY MSG1
        MOV SI, OFFSET FNAME
BACK:   MOV AH, 01H
        INT 21H
        CMP AL, 0DH
        JE NEXT
        MOV [SI], AL
        INC SI
        JMP BACK
NEXT  : MOV [SI], BYTE PTR '$'
        LEA DX, FNAME
        MOV CX, 00H    
        MOV AH, 3CH             ; INTERRUPT FOR FILE CREATION
        INT 21H
        JC FAILED
        DISPLAY MSG2
        JMP NEXT1
FAILED: DISPLAY MSG3
NEXT1:  DISPLAY MSG4
        MOV SI, OFFSET FNAME2
BACK1:  MOV AH, 01H
        INT 21H
        CMP AL, 0DH
        JE NEXT2
        MOV [SI], AL
        INC SI
        JMP BACK1
NEXT2 : MOV [SI], BYTE PTR '$'
        LEA DX, FNAME2
        MOV AH, 41H             ; INTERRUPT FOR FILE DELETION
        INT 21H
        JC DFAIL
        DISPLAY MSG5
        JMP FINAL
DFAIL : DISPLAY MSG6
FINAL : MOV AH, 4CH
        INT 21H
END START
